ARG REGISTRY_ID

FROM cr.yandex/${REGISTRY_ID}/backend-develop:latest AS backend-develop-tests-builder

RUN apt-get update && apt-get install -y \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /project

# Copy code
COPY . .

RUN mkdir -p build \
    && mv /project/vcpkg_installed build/

RUN cmake -B build -S . \
      -DPLATFORM=BACKEND \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_TESTING=ON \
      -DVCPKG_TARGET_TRIPLET=x64-linux \
    && cd build \
    && cmake --build . -j$(nproc)


FROM ubuntu:24.04 AS backend-develop-tests

RUN apt-get update && apt-get install -y \
    cmake \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /project
COPY --from=backend-develop-tests-builder /project/build /project/build
