ARG REGISTRY_ID

FROM cr.yandex/${REGISTRY_ID}/backend-develop:latest

RUN apt-get update && apt-get install -y \
    ca-certificates
    && rm -rf /var/lib/apt/lists/*

WORKDIR /project

# Copy code
COPY . .

RUN mkdir -p build \
    && cp -r /project/vcpkg_installed build/

RUN cmake -B build -S . \
      -DPLATFORM=BACKEND \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_TESTING=ON \
      -DVCPKG_TARGET_TRIPLET=x64-linux \
    && cd build \
    && cmake --build . -j$(nproc)

RUN FILES=$(find . -type f \( -name "*.cpp" -o -name "*.h" -o -name "*.hpp" \) \
    -not -path "./build/*" -not -path "./vcpkg/*") && \
    if [ -f ".clang-tidy" ] && [ ! -z "$FILES" ]; then \
      echo "Running clang-tidy..." && \
      cd build && run-clang-tidy -p . $FILES; \
    fi

RUN cd /project/build && ctest --output-on-failure
