find_program(conanexecutable "conan")
if(NOT conanexecutable)
  message(WARNING "Tool conan is not installed. Check README.md for build instructions without conan.")
else()
  message(STATUS "Found conan. Installing dependencies.")
  if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan_provider.cmake")
    message(STATUS "Downloading conan_provider.cmake from https://github.com/conan-io/cmake-conan")
    file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/develop2/conan_provider.cmake"
                  "${CMAKE_BINARY_DIR}/conan_provider.cmake")
  endif()
  message(STATUS "Using downloaded conan_provider.cmake")
  include(${CMAKE_BINARY_DIR}/conan_provider.cmake)
endif()
