macro(EXECUTABLE)
    if(ARGC GREATER 1)
        message(FATAL_ERROR "Macro EXECUTABLE: Bad args")
    endif()
    set(SUIT "EXECUTABLE")
    set(EXECUTABLE_NAME ${ARGV0})
    set(SOURCES )
    set(LIBRARIES )
endmacro()

macro(LIBRARY)
    if(ARGC GREATER 1)
        message(FATAL_ERROR "Macro LIBRARY: Bad args")
    endif()
    set(SUIT "LIBRARY")
    set(LIBRARY_NAME ${ARGV0})
    set(LIBRARY_PARAM ${ARGV1})
    set(SOURCES )
    set(LIBRARIES )
endmacro()

macro(GTEST)
    if(ARGC GREATER 1)
        message(FATAL_ERROR "Macro GTEST: Bad args")
    endif()
    set(SUIT "GTEST")
    set(GTEST_NAME ${ARGV0})
    set(SOURCES )
    set(LIBRARIES )
endmacro()

macro(SRCS)
    set(SOURCES ${ARGN})
endmacro()

macro(LIBS)
    set(LIBRARIES ${ARGN})
endmacro()

macro(END)
    if(SUIT STREQUAL "GTEST")
        add_executable(${GTEST_NAME}_test ${SOURCES})
        target_link_libraries(${GTEST_NAME}_test PUBLIC ${LIBRARIES} GTest::GTest GTest::Main)

        add_test(
            NAME ${GTEST_NAME}
            COMMAND ${GTEST_NAME}_test
        )
    elseif(SUIT STREQUAL "LIBRARY")
        add_library(${LIBRARY_NAME} ${LIBRARY_PARAM})
        target_sources(${LIBRARY_NAME} PRIVATE ${SOURCES})
        if(NOT ${LIBRARY_PARAM} STREQUAL "INTERFACE")
          set(LIBRARY_PARAM "PUBLIC")
        endif()
        target_link_libraries(${LIBRARY_NAME} ${LIBRARY_PARAM} ${LIBRARIES})
    elseif(SUIT STREQUAL "EXECUTABLE")
        add_executable(${EXECUTABLE_NAME})
        target_sources(${EXECUTABLE_NAME} PRIVATE ${SOURCES})
        target_link_libraries(${EXECUTABLE_NAME} PUBLIC ${LIBRARIES})
    else()
        message(FATAL_ERROR "Error")
    endif()

    set(SUIT "")
endmacro()

macro(ADD_TESTS)
    if(ARGC GREATER 1)
        message(FATAL_ERROR "Macro ADD_TESTS: Bad args")
    endif()
    if(BUILD_TESTING)
        add_subdirectory(${ARGV0})
    endif()
endmacro()
