name: Build Backend Docker Image

on:
  push:
    branches: [ main, master ]
    paths:
      - 'vcpkg.json'
      - 'docker/backend-dev/Dockerfile'
  workflow_dispatch:

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Yandex Container Registry
        run: |
          echo ${{ secrets.YANDEX_REGISTRY_TOKEN }}|docker login \
            --username oauth \
            --password-stdin \
            cr.yandex
      
      - name: Build Backend Docker image
        run: |
          docker build -t backend-develop -f ./docker/backend-dev/Dockerfile .

      - name: Tag and push backend image
        run: |
          VERSION=$(cat .version)
          docker tag backend-develop cr.yandex/${{ secrets.YANDEX_REGISTRY_IDENTITY }}/backend-develop:$VERSION
          docker tag backend-develop cr.yandex/${{ secrets.YANDEX_REGISTRY_IDENTITY }}/backend-develop:latest
          
          docker push cr.yandex/${{ secrets.YANDEX_REGISTRY_IDENTITY }}/backend-develop:$VERSION
          docker push cr.yandex/${{ secrets.YANDEX_REGISTRY_IDENTITY }}/backend-develop:latest
