name: Build Backend Docker Image

on:
  push:
    branches: [ main, master ]
    paths:
      - 'vcpkg.json'
  workflow_dispatch:

jobs:
  check_commit:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check commit message and file changes
        id: check
        run: |
          # If changed vcpkg.json
          if git diff --name-only HEAD^ HEAD | grep -q "vcpkg.json"; then
            echo "vcpkg.json was changed"
            echo "should_run=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # If commit contains [run-docker-build]
          if git log -1 --pretty=%B | grep -q "\[run-docker-build\]"; then
            echo "Commit message contains [run-docker-build] tag"
            echo "should_run=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # If runs manually. Event = workflow_dispatch
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Workflow triggered manually"
            echo "should_run=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "No conditions met for build"
          echo "should_run=false" >> $GITHUB_OUTPUT

  build_backend:
    needs: check_commit
    if: needs.check_commit.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Yandex Container Registry
        run: |
          echo ${{ secrets.YANDEX_REGISTRY_TOKEN }}|docker login \
            --username oauth \
            --password-stdin \
            cr.yandex

      - name: Build Backend Docker image
        run: |
          docker build -t backend-develop -f ./docker/backend-dev/Dockerfile .

      - name: Tag and push backend image
        run: |
          VERSION=$(cat .version)
          docker tag backend-develop cr.yandex/${{ secrets.YANDEX_REGISTRY_IDENTITY }}/backend-develop:${VERSION}
          docker tag backend-develop cr.yandex/${{ secrets.YANDEX_REGISTRY_IDENTITY }}/backend-develop:latest
          
          docker push cr.yandex/${{ secrets.YANDEX_REGISTRY_IDENTITY }}/backend-develop:${VERSION}
          docker push cr.yandex/${{ secrets.YANDEX_REGISTRY_IDENTITY }}/backend-develop:latest
