name: Build Android Dependencies Docker Image

on:
  push:
    branches: [ main, master ]
    paths:
      - 'vcpkg.json'
      - 'docker/android-dev/Dockerfile'
  workflow_dispatch:

jobs:
  build_android:
    runs-on: self-hosted # Fails on github runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Yandex Container Registry
        run: |
          echo ${{ secrets.YANDEX_REGISTRY_TOKEN }}|docker login \
            --username oauth \
            --password-stdin \
            cr.yandex
      
      - name: Build Android Docker image
        run: |
          docker build -t android-develop -f ./docker/android-dev/Dockerfile .

      - name: Tag and push android image
        run: |
          VERSION=$(cat .version)
          docker tag android-develop cr.yandex/${{ secrets.YANDEX_REGISTRY_IDENTITY }}/android-develop:$VERSION
          docker tag android-develop cr.yandex/${{ secrets.YANDEX_REGISTRY_IDENTITY }}/android-develop:latest
          
          docker push cr.yandex/${{ secrets.YANDEX_REGISTRY_IDENTITY }}/android-develop:$VERSION
          docker push cr.yandex/${{ secrets.YANDEX_REGISTRY_IDENTITY }}/android-develop:latest
