name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  check_commit:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check commit message and file changes
        id: check
        run: |
          echo "should_run=true" >> $GITHUB_OUTPUT

          # If runs manually. Event = workflow_dispatch
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Workflow triggered manually"
            exit 0
          fi

          # If commit contains [no-run-build-backend]
          if git log -1 --pretty=%B | grep -q "\[no-run-build-backend\]"; then
            echo "Commit message contains [no-run-build-backend] tag"
            echo "should_run=false" >> $GITHUB_OUTPUT
            exit 0
          fi

  build_and_test:
    needs: check_commit
    if: needs.check_commit.outputs.should_run == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Free disk space
        run: |
          sudo apt-get clean
          docker system prune -af

      - name: Login to Yandex Container Registry
        uses: docker/login-action@v2
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.YANDEX_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Build project image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/backend-dev/Dockerfile.building
          build-args: |
            REGISTRY_ID=${{ secrets.YANDEX_REGISTRY_IDENTITY }}
          push: false
          load: true
          tags: backend-develop-tests:latest
          no-cache: true
          provenance: false

      - name: Run tests
        run: |
          docker run --rm backend-develop-tests:latest \
            /bin/bash -c '
              set -e

              cd build
              ctest -C Release --output-on-failure -j$(nproc)
              echo "Tests completed successfully"
            '

      - name: Extract build artifacts
        run: |
          CONTAINER_ID=$(docker create backend-develop-tests:latest)

          mkdir -p ./artifacts
          docker cp $CONTAINER_ID:/project/build/backend/backend_main ./artifacts/ || true

          docker rm $CONTAINER_ID

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./artifacts
          retention-days: 7
