name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Yandex Container Registry
        uses: docker/login-action@v2
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.YANDEX_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build project image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/backend-dev/Dockerfile.building
          build-args: |
            REGISTRY_ID=${{ secrets.YANDEX_REGISTRY_IDENTITY }}
          push: false
          load: true
          tags: backend-develop-tests:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        run: |
          docker run --rm backend-develop-tests:latest \
            /bin/bash -c '
              set -e

              cd build
              ctest -C Release --output-on-failure -j$(nproc)
              echo "Tests completed successfully"
            '

      - name: Extract build artifacts
        run: |
          CONTAINER_ID=$(docker create backend-develop-tests:latest)

          mkdir -p ./artifacts
          docker cp $CONTAINER_ID:/project/build/backend/backend_main ./artifacts/ || true

          docker rm $CONTAINER_ID

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./artifacts
          retention-days: 7
